### ISSUE TITLE
Does not comply with Thunderstore format

### ISSUE THREAD

**Issue by laundmo** [QuartzShard/lmao.box#2]
# Does not comply with Thunderstore format

Thunderstore link: https://northstar.thunderstore.io/package/we_commit_coding_felonies/lmao_box/

This mod does not comply with the Thunderstore format and will therefore fail to install when using a mod manager.

Please refer to this guide for the correct format https://r2northstar.gitbook.io/r2northstar-wiki/modding-and-development/modding/publishing

Or alternatively take a look at this example repository: https://github.com/laundmo/northstar-mod-template

**Comment by QuartzShard** [comment]
Fixed as of [this commit](https://github.com/we-commit-coding-felonies/lmao.box/commit/f10141f263ac22200d8e0d21b1fc9f5ce73afbe3)
